---
sudo: required

services:
  - docker

script:
- container_id=$(mktemp)
- 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-condor_client:ro centos-7:ansible > "${container_id}"'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-condor_client/test.yml -i /etc/ansible/roles/ansible-role-condor_client/tests/inventory --syntax-check'
- 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-condor_client/test.yml  -i /etc/ansible/roles/ansible-role-condor_client/tests/inventory'

before_install:
  - 'sudo docker pull centos:7}'
  - 'sudo docker build --no-cache --rm --file=test/Dockerfile --tag=centos-7:ansible travis'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/