---
# tasks file for ansible-role-condor_client

- name: download repos and keys
  become: yes
  get_url: 
    url: "{{ item.source }}"
    dest: "{{ item.dest }}"
  with_items:
    - { source: 'http://linuxsoft.cern.ch/wlcg/RPM-GPG-KEY-wlcg', dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-wlcg' }
    - { source: 'http://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo', dest: '/etc/yum.repos.d/htcondor-stable-rhel7.repo' }
    - { source: 'http://repository.egi.eu/community/software/preview.repository/2.0/releases/repofiles/centos-7-x86_64.repo', dest: '/etc/yum.repos.d/centos-7-x86_64.repo' }
    - { source: 'http://linuxsoft.cern.ch/wlcg/wlcg-centos7.repo', dest: '/etc/yum.repos.d/wlcg-centos7.repo' }
    - { source: 'http://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor', dest: '/etc/pki/rpm-gpg/RPM-GPG-KEY-HTCondor' }
    - { source: 'https://ci.cloud.cnaf.infn.it/view/dodas/job/ca_DODAS-TTS/job/master/lastSuccessfulBuild/artifact/ca_DODAS-TTS.repo',  dest: '/etc/yum.repos.d/ca_DODAS-TTS.repo'}

- name: install condorkey
  become: yes
  command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-HTCondor

- name: install packages
  become: yes
  yum:
    name:
    - yum-plugin-ovl
    - fetch-crl
    - wn
    - condor-all-8.8.2-1.el7
    - ca_DODAS-TTS
    - jq
    state: present

- name: Compile condor client config and utilities
  become: yes
  template:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { source: 'templates/condor_config', dest: '/etc/condor/condor_config' }
    - { source: 'templates/get_proxy.py', dest: '/home/centos/get_proxy.py' }
    - { source: 'templates/get_proxy.sh', dest: '/home/centos/get_proxy.sh' }

- name: copy job example
  become: yes
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { source: 'files/simple-job.sh', dest: '/home/centos/simple-job.sh' }
    - { source: 'files/simple-job.sub', dest: '/home/centos/simple-job.sub' }
